### ISSUE TITLE
报错 “KeyError: 'iconList'” 无法发布

### ISSUE THREAD

**Issue by AlbertWang2018** [Meekdai/Gmeek-template#3]
今天遇到了 报错 “KeyError: 'iconList'” 无法发布 ，不知道怎么解决。
![Snipaste_2024-03-26_20-01-14](https://github.com/Meekdai/Gmeek-template/assets/36392874/23610216-5776-4dc8-85c9-75c1c29a3ae5)

**Comment by Meekdai** [comment]
@AlbertWang2018 今天更新了可以自定义icon的功能，你可以全局手动生成一次就可以了。

**Comment by AlbertWang2018** [comment]
> @AlbertWang2018 今天更新了可以自定义icon的功能，你可以全局手动生成一次就可以了。

非常感谢，通过Actions->build Gmeek->Run workflow->里面的按钮全局重新生成一次，解决了问题。
