### ISSUE TITLE
建议workflow监听更多issue状态变更

### ISSUE THREAD

**Issue by supery-chen** [Meekdai/Gmeek-template#4]
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#issues

![image](https://github.com/Meekdai/Gmeek-template/assets/54849153/de3c6ce9-6bd3-46c2-b5cb-7c08a9d13b00)

**Comment by Meekdai** [comment]
@supery-chen 这个之前有研究过，监听太多会导致一口气执行太多Actions，容易出错。
