### ISSUE TITLE
有两个问题咨询

### ISSUE THREAD

**Issue by qubick14** [Meekdai/Gmeek-template#8]
![image](https://github.com/Meekdai/Gmeek-template/assets/7146262/51998c36-7cd2-4343-b288-d275efe59839)
按照 教程生成的页面 风格和主体比较奇怪，是script 和CSS 问题么？

另一个问题是，按照教程生成的域名 是 前缀有 自己 仓库名字 的。例如 
https://qubick14.github.io/qubick 这样的，而不是 介绍的 域名。
![image](https://github.com/Meekdai/Gmeek-template/assets/7146262/f446f3b6-c0b2-4fd7-92fc-d5d3abe6284f)

**Comment by Meekdai** [comment]
1、我现在看很正常啊。
2、建议仓库名称为`XXX.github.io`。你需要设置你的仓库名称为`qubick14.github.io`，而不是`qubick`

**Comment by qubick14** [comment]
第一个问题，奇怪的是 好像CSS JS 没有加载，没有样式应用成功。请问下作者 这个 JS 和CSS 需要单独 设置么？

**Comment by Meekdai** [comment]
我这里看很正常啊，你换个浏览器试试。
![image](https://github.com/Meekdai/Gmeek-template/assets/11755104/3bbc23cf-b291-4238-a18d-c72835c9e823)

**Comment by qubick14** [comment]
好的谢谢，确实之前是不正常的，我刚才换了个浏览器是正常的，然后切换回之前的edge 浏览器也正常了。不确定是什么问题。
